# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyvdV1cjEXh8f3djp-JOdMCAm2xmzDFW

### Dashboard Air Quality

Dashboard ini didesain untuk menganalisis dua aspek kunci kualitas udara:
1.  **Tren Konsentrasi Karbon Monoksida (CO) antara Hari Kerja dan Akhir Pekan:**
    *   Menjelajahi bagaimana rata-rata konsentrasi CO di pusat kota berfluktuasi dari hari kerja ke akhir pekan.
    *   Menyoroti peningkatan CO yang terjadi baik pada jam sibuk maupun jam non-sibuk di akhir pekan, menunjukkan dampak aktivitas akhir pekan terhadap kualitas udara.

2.  **Kondisi Kritis Nitrogen Dioksida (NO2) di Musim Dingin:**
    *   Memvisualisasikan insiden konsentrasi NO2 yang tinggi (di atas 80 µg/m³) yang bertepatan dengan kecepatan angin rendah (di bawah 1.5 m/s).
    *   Fokus pada hari kerja musim dingin, periode di mana kondisi ini sangat umum dan berkontribusi secara signifikan pada tantangan kualitas udara akibat terhambatnya penyebaran polutan.
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- 1. Konfigurasi Halaman Streamlit ---
st.set_page_config(page_title="Dashboard Kualitas Udara", layout="wide")
st.title("Dashboard Analisis Kualitas Udara")
st.markdown("### Menjawab Pertanyaan Bisnis Kualitas Udara")

# --- 2. Memuat Data ---
file_path = 'air_quality_combined.zip'
try:
    df = pd.read_csv(file_path, compression='zip')
except FileNotFoundError:
    st.error(f"Error: File '{file_path}' not found. Please upload the file.")
    st.stop() # Stop the app if file is not found
except Exception as e:
    st.error(f"An error occurred while loading the dataset: {e}")
    st.stop() # Stop the app if there's an error

# --- 3. Pra-pemrosesan Data ---
df['datetime'] = pd.to_datetime(df['datetime'])
df['day_of_week_name'] = df['datetime'].dt.day_name()
# Ensure 'is_weekday' is Boolean for clearer logic
df['is_weekday'] = ~df['day_of_week_name'].isin(['Saturday', 'Sunday'])
df['hour'] = df['datetime'].dt.hour

# --- 4. Analisis Pertanyaan Bisnis 1: Tren CO (Hari Kerja vs. Akhir Pekan) ---
st.header("Pertanyaan 1: Tren CO dari Hari Kerja ke Akhir Pekan di Pusat Kota")
st.markdown("Bagaimana transisi dari hari kerja (Senin-Jumat) ke akhir pekan (Sabtu-Minggu) memengaruhi rata-rata tingkat Karbon Monoksida (CO) di pusat kota dan apakah kenaikan ini terjadi di semua jam atau hanya pada jam sibuk?")

# Asumsi: 'Dongsi' sebagai representasi pusat kota
central_city_station = 'Dongsi'
if central_city_station not in df['station'].unique():
    st.warning(f"Stasiun '{central_city_station}' tidak ditemukan. Menggunakan semua stasiun untuk analisis CO.")
    df_q1 = df.copy()
else:
    df_q1 = df[df['station'] == central_city_station].copy()

# Definisikan jam sibuk dan jam non-sibuk
busy_hours = [7, 8, 9, 17, 18, 19] # 7-9 AM dan 5-7 PM
df_q1['is_busy_hour'] = df_q1['hour'].isin(busy_hours)

if not df_q1.empty:
    # Rata-rata CO berdasarkan Hari Kerja/Akhir Pekan
    avg_co_overall = df_q1.groupby('is_weekday')['CO'].mean().reset_index()
    avg_co_overall['type'] = avg_co_overall['is_weekday'].apply(lambda x: 'Hari Kerja' if x else 'Akhir Pekan')

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("CO Rata-rata Hari Kerja", f"{avg_co_overall[avg_co_overall['is_weekday'] == True]['CO'].iloc[0]:.2f} µg/m³")
    with col2:
        st.metric("CO Rata-rata Akhir Pekan", f"{avg_co_overall[avg_co_overall['is_weekday'] == False]['CO'].iloc[0]:.2f} µg/m³")
    with col3:
        co_weekday = avg_co_overall[avg_co_overall['is_weekday'] == True]['CO'].iloc[0]
        co_weekend = avg_co_overall[avg_co_overall['is_weekday'] == False]['CO'].iloc[0]
        percentage_increase_overall = ((co_weekend - co_weekday) / co_weekday) * 100 if co_weekday != 0 else 0
        st.metric("Peningkatan CO (Overall)", f"{percentage_increase_overall:.2f} %", delta_color="inverse")

    st.subheader("Peningkatan CO berdasarkan Jam Sibuk dan Non-Sibuk")
    avg_co_hourly = df_q1.groupby(['is_weekday', 'is_busy_hour'])['CO'].mean().reset_index()

    # Calculate percentage increase for busy hours
    co_weekday_busy = avg_co_hourly[(avg_co_hourly['is_weekday'] == True) & (avg_co_hourly['is_busy_hour'] == True)]['CO'].iloc[0]
    co_weekend_busy = avg_co_hourly[(avg_co_hourly['is_weekday'] == False) & (avg_co_hourly['is_busy_hour'] == True)]['CO'].iloc[0]
    percentage_increase_busy = ((co_weekend_busy - co_weekday_busy) / co_weekday_busy) * 100 if co_weekday_busy != 0 else 0

    # Calculate percentage increase for non-busy hours
    co_weekday_non_busy = avg_co_hourly[(avg_co_hourly['is_weekday'] == True) & (avg_co_hourly['is_busy_hour'] == False)]['CO'].iloc[0]
    co_weekend_non_busy = avg_co_hourly[(avg_co_hourly['is_weekday'] == False) & (avg_co_hourly['is_busy_hour'] == False)]['CO'].iloc[0]
    percentage_increase_non_busy = ((co_weekend_non_busy - co_weekday_non_busy) / co_weekday_non_busy) * 100 if co_weekday_non_busy != 0 else 0

    col_q1_1, col_q1_2 = st.columns(2)
    with col_q1_1:
        st.metric("Peningkatan CO (Jam Sibuk)", f"{percentage_increase_busy:.2f} %", delta_color="inverse")
    with col_q1_2:
        st.metric("Peningkatan CO (Jam Non-Sibuk)", f"{percentage_increase_non_busy:.2f} %", delta_color="inverse")

    st.markdown("**Kesimpulan Pertanyaan 1:** Rata-rata konsentrasi Karbon Monoksida (CO) di pusat kota menunjukkan peningkatan dari hari kerja ke akhir pekan. Peningkatan ini terjadi baik pada jam sibuk maupun jam non-sibuk, mengindikasikan bahwa aktivitas di akhir pekan tetap berkontribusi pada peningkatan kadar CO, bukan penurunan seperti yang mungkin diasumsikan.")

    # Visualisasi Tren CO per Jam
    st.subheader("Tren Rata-rata CO per Jam (Hari Kerja vs. Akhir Pekan)")
    co_hourly_trend = df_q1.groupby(['hour', 'is_weekday'])['CO'].mean().reset_index()
    co_hourly_trend['Day Type'] = co_hourly_trend['is_weekday'].apply(lambda x: 'Weekday' if x else 'Weekend')

    fig1, ax1 = plt.subplots(figsize=(12, 6))
    sns.lineplot(data=co_hourly_trend, x='hour', y='CO', hue='Day Type', marker='o', ax=ax1)
    ax1.set_title("Rata-rata Konsentrasi CO per Jam")
    ax1.set_xlabel("Jam (0-23)")
    ax1.set_ylabel("Rata-rata CO (µg/m³)")
    ax1.set_xticks(range(0, 24))
    ax1.grid(True, linestyle='--', alpha=0.7)
    st.pyplot(fig1)
    plt.close(fig1)

else:
    st.warning("Tidak ada data CO yang tersedia untuk analisis pusat kota.")

st.markdown("--- ")

# --- 5. Analisis Pertanyaan Bisnis 2: Kondisi Kritis NO2 di Musim Dingin ---
st.header("Pertanyaan 2: Kondisi Kritis NO2 di Hari Kerja Musim Dingin")
st.markdown("Berapa presentasi waktu (dalam jam) dan total hari terjadinya kondisi saat konsentrasi NO2 melampaui 80 µg/m³ bersamaan dengan kecepatan angin di bawah 1.5 m/s pada hari kerja selama musim dingin?")

# Filter data untuk kondisi spesifik
df_q2 = df[(df['NO2'] > 80) &
           (df['WSPM'] < 1.5) &
           (df['is_weekday'] == True) &
           (df['season'] == 'Winter')].copy()

# Hitung total jam dan total hari kritis
critical_hours = len(df_q2)
critical_days = df_q2['datetime'].dt.date.nunique()

# Hitung total jam dan total hari kerja selama musim dingin sebagai basis persentase
total_winter_weekday_data = df[(df['is_weekday'] == True) & (df['season'] == 'Winter')]
total_winter_weekday_hours = len(total_winter_weekday_data)
total_winter_weekday_days = total_winter_weekday_data['datetime'].dt.date.nunique()

percentage_hours = (critical_hours / total_winter_weekday_hours) * 100 if total_winter_weekday_hours != 0 else 0
percentage_days = (critical_days / total_winter_weekday_days) * 100 if total_winter_weekday_days != 0 else 0

col_q2_1, col_q2_2, col_q2_3, col_q2_4 = st.columns(4)
with col_q2_1:
    st.metric("Total Jam Kritis NO2", f"{critical_hours} jam")
with col_q2_2:
    st.metric("Total Hari Kritis NO2", f"{critical_days} hari")
with col_q2_3:
    st.metric("Persentase Waktu Kritis", f"{percentage_hours:.2f} %", delta_color="inverse")
with col_q2_4:
    st.metric("Persentase Hari Kritis", f"{percentage_days:.2f} %", delta_color="inverse")

st.markdown("**Kesimpulan Pertanyaan 2:** Selama hari kerja musim dingin, kondisi kritis konsentrasi NO2 tinggi (di atas 80 µg/m³) yang disertai dengan kecepatan angin rendah (di bawah 1.5 m/s) sering terjadi. Kondisi ini menyumbang sekitar **{:.2f}% dari total jam** dan berdampak pada **{:.2f}% dari semua hari kerja musim dingin** yang substansial. Persentase hari yang tinggi ini menunjukkan bahwa kondisi lingkungan seperti itu merupakan karakteristik hari kerja musim dingin dan kemungkinan berkontribusi pada tantangan kualitas udara yang persisten, karena kecepatan angin yang rendah menghambat penyebaran polutan.".format(percentage_hours, percentage_days))

st.markdown("--- ")

st.subheader("Distribusi Jam Kritis NO2")
if not df_q2.empty:
    critical_hour_distribution = df_q2['hour'].value_counts().sort_index()
    fig2, ax2 = plt.subplots(figsize=(10, 5))
    sns.barplot(x=critical_hour_distribution.index, y=critical_hour_distribution.values, ax=ax2, palette='viridis')
    ax2.set_title("Distribusi Jam dengan Kondisi Kritis NO2 Tinggi (Hari Kerja Musim Dingin)")
    ax2.set_xlabel("Jam (0-23)")
    ax2.set_ylabel("Jumlah Kejadian")
    ax2.set_xticks(range(0, 24))
    ax2.grid(axis='y', linestyle='--', alpha=0.7)
    st.pyplot(fig2)
    plt.close(fig2)
else:
    st.info("Tidak ada kejadian kondisi kritis NO2 yang ditemukan untuk hari kerja musim dingin.")


st.markdown("--- ")

st.info("**Catatan:** Untuk menjalankan aplikasi Streamlit ini secara lokal, simpan kode di atas sebagai file Python (`.py`), misalnya `dashboard_kualitas_udara.py`. Kemudian, buka terminal Anda, navigasi ke direktori tempat Anda menyimpan file tersebut, dan jalankan perintah `streamlit run dashboard_kualitas_udara.py`.")